Routes & Controller responses updated
julian-er/nutrition-api-pp2 pull request #8
Opened 2022-09-18 18:51 UTC by mggaray

please review and approve if there are no problems

2022-09-19 00:13 UTC, julian-er commented
I can't approve this merge, for now. We have some issues. Please resolve this and let me know! 😄

2022-09-19 23:17 UTC, julian-er requested changes

2022-09-19 23:17 UTC, julian-er commented on src/controllers/foods.js
> +	async getByFoodName(req, res) {
Why should you change this name? this is a method to query by name but not return an hhtp response.
In fact, you should have a getFoodByName function that uses this method and then returns a response like in the user's handlers.

2022-09-19 23:17 UTC, julian-er commented on src/controllers/allergies.js
> +	getAllegyById(req, res) {
Please correct the typo, you are trying to use this function in the router because of this it will not work 😞

2022-09-19 23:17 UTC, julian-er commented on src/controllers/allergies.js
> +	getAllegyById(req, res) {
Also... please you can fix the typo on line 10 too?

2022-09-19 23:17 UTC, julian-er commented on src/controllers/allergies.js
> +	async getByAllergyName(req, res) {
Why should you change this name? this is a method to query by name but not return an HTTP response.
In fact, you should have a getByAllergyName function that uses this method and then returns a response like in the user's handlers.

2022-09-19 23:17 UTC, julian-er commented on src/routes/allergies.js
> +	router.get('/allergies/:id', (req, res) => controller.getAllergyById(req, res));
Fix the typo on the allergies controller and this will work

2022-09-19 23:17 UTC, julian-er commented on src/routes/allergies.js
> +	router.get('/allergies/:id', (req, res) => controller.getAllergyById(req, res));
Test review

2022-09-20 04:21 UTC, mggaray commented on src/controllers/allergies.js
> +	getAllegyById(req, res) {
resolved

2022-09-20 04:21 UTC, mggaray commented on src/routes/allergies.js
> +	router.get('/allergies/:id', (req, res) => controller.getAllergyById(req, res));
resolved

2022-09-20 04:21 UTC, mggaray commented on src/controllers/foods.js
> +	async getByFoodName(req, res) {
fixed

2022-09-20 04:21 UTC, mggaray commented on src/controllers/allergies.js
> +	async getByAllergyName(req, res) {
done

2022-09-21 23:42 UTC, julian-er commented
@mggaray the branch has conflicts, maybe you need to try marge main first

2022-09-22 00:26 UTC, julian-er approved these changes
Great !

2022-09-22 00:34 UTC, AdanVolken approved these changes
good job !!

2022-09-22 00:59 UTC, merged