Adan-branch_ Incorporate Diets
julian-er/nutrition-api-pp2 pull request #9
Opened 2022-09-19 00:51 UTC by AdanVolken

I add diets to controllers and routes

2022-09-19 01:01 UTC, julian-er commented
Update the answers to the new approach as it happens in the users controller in the main branch @AdanVolken

2022-09-19 01:01 UTC, julian-er requested changes
Update the answers to the new approach as it happens in the users controller in the main branch @AdanVolken

2022-09-19 02:05 UTC, julian-er approved these changes

2022-09-20 03:21 UTC, gobu-github approved these changes
The changes seem correct!

2022-09-20 03:32 UTC, merged